# Google App Engine configuration for Point6 static website
runtime: nodejs20

handlers:
  # Serve static assets with long cache
  - url: /css
    static_dir: dist/css
    expiration: "30d"

  - url: /js
    static_dir: dist/js
    expiration: "30d"

  - url: /assets
    static_dir: dist/assets
    expiration: "30d"

  # Robots and sitemap
  - url: /robots\.txt
    static_files: dist/robots.txt
    upload: dist/robots\.txt
    expiration: "1d"

  - url: /sitemap\.xml
    static_files: dist/sitemap.xml
    upload: dist/sitemap\.xml
    expiration: "1d"

  - url: /site\.webmanifest
    static_files: dist/site.webmanifest
    upload: dist/site\.webmanifest

  # HTML pages (clean URLs)
  - url: /services
    static_files: dist/services.html
    upload: dist/services\.html

  - url: /about
    static_files: dist/about.html
    upload: dist/about\.html

  - url: /contact
    static_files: dist/contact.html
    upload: dist/contact\.html

  - url: /results
    static_files: dist/results.html
    upload: dist/results\.html

  - url: /ai-launchpad
    static_files: dist/ai-launchpad.html
    upload: dist/ai-launchpad\.html

  # Homepage
  - url: /
    static_files: dist/index.html
    upload: dist/index\.html

  # Fallback for .html extension
  - url: /(.+)\.html
    static_files: dist/\1.html
    upload: dist/(.+)\.html

error_handlers:
  - file: dist/404.html
